version: "3"
services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "8000:8000"
    tty: true
    networks:
      - python
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data:cached
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
networks:
  python:
    name: python
