# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /tests

COPY requirements-test.txt requirements-test.txt
RUN pip3 install -r requirements-test.txt

COPY . .

CMD ["pytest", "-sv", "--html=report.html"]
