version: 2.1

orbs:
  python: circleci/python@1.2
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: rm -f "package.zip"
      - run: pip3 install --platform manylinux2014_x86_64 --implementation cp --python-version 3.9 --only-binary=':all:' --upgrade -r "src/requirements.txt" --target "package"
      - run: cp -r src package/src
      - run: cd "package" && zip -r "../package.zip" * -x '*__pycache__*'
      - run: zip -r "./package.zip" "./src" -x '*__pycache__*' '*aws-sam*'
      - run: rm -rf "package"
      - persist_to_workspace:
            root: .
            paths:
              - .
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run: aws lambda update-function-code --function-name flask-lambda --zip-file fileb://package.zip
workflows:
  master:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context:
            - aws

